### ISSUE TITLE
@AndroidPreference minor dep issue

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#63] opened 2015-01-09 15:41 UTC
Hi,

While hacking at [XtendApp](https://github.com/Buggaboo/XtendApp), I bumped into a minor deps issue wrt `@AndroidPreference`. It has an implicit dependency on guava.

I think we should mention this somewhere in the documentation.

The fix:

``` gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.2'
    //compile 'com.github.tobykurien:xtendroid:0.11.+'
    xtendCompileOnly 'org.eclipse.xtend:org.eclipse.xtend.lib:2.7.+'
    compile 'org.eclipse.xtext:org.eclipse.xtext.xbase.lib.slim:2.7.+'
    compile 'com.google.guava:guava:18.+' // <-- this dependency is required for @AndroidPreference magic
}
```

Thanks!

**Comment by tobykurien** [comment] 2015-01-11 08:54
Thanks for logging the issue, I'll try to remove the dependency on Guava since it bloats the runtime.

**Comment by Buggaboo** [comment] 2015-01-13 14:31
Great!

**Comment by tobykurien** [comment] 2015-03-31 07:16
I don't see any dependency to Guava in the ```@AndroidPreference``` code, so I'm not sure what the problem is. Can you dump the compile error?

**Comment by Buggaboo** [comment] 2015-03-31 13:27
Maybe it was removed already? Dunno.

Try checking out XtendApp from master and outcomment guava in the deps from build.gradle.
Maybe a false positive, the IDE (i.e. pre-alpha Xtend plugin) might be the culprit.

**Comment by tobykurien** [comment] 2015-04-01 08:30
Aah I see the problem, I'll look into it.

**Comment by tobykurien** [comment] 2017-02-14 10:21
Closing this issue because xtend slim library doesn't seem to be supported anymore (no version 2.11)

**Closed by tobykurien** 2017-02-14 10:21 UTC
