### ISSUE TITLE
github.io/xtendroid, also how we managed to get Xtendroid to work on Intellij and Android Studio

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#81] opened 2015-07-27 12:13 UTC
Heya,

Here's an idea to improve the visibility of Xtendroid:

We should setup a [github page](https://pages.github.com/) for xtendroid.

Just some static pages demonstrating the power of Xtend and Xtendroid, with properly formatted code, with screenshots.

This shouldn't very hard to do with [Bootstrap](http://getbootstrap.com/2.3.2/).

Thoughts? Suggestions?

**Comment by szarnekow** [comment] 2015-07-29 08:19
:+1: would be cool to also show some advantages compared to pure Java or other languages that claim to make life easier for Androids

**Comment by tobykurien** [comment] 2015-08-04 07:37
I like the idea. It also is a good place to document some of the design patterns enabled by using Xtend.

**Comment by Buggaboo** [comment] 2015-09-18 14:26
Ugh, I tried reviving my xtendroid projects on android studio (AS), and the plugins are beyond broken.

Does anyone have a stable version running? I'm on canary (bleeding edge AS), and I upgraded the plugins to the latest.

**Comment by tobykurien** [comment] 2015-09-18 14:41
My advise is to stick with Eclipse and use the eclipse-aar-gradle plugin as mentioned in the README.

**Comment by Buggaboo** [comment] 2015-09-18 15:00
Will do. Thanks.

**Comment by svenefftinge** [comment] 2015-09-18 22:13
Android Studio is currently using an older build of the idea platform, than
we do. So there are some incompatibilities. They will soon upgrade, in the
meantime you can also use IntelliJ IDEA 15 EAP and install one of the
latest nightlies. We are going to release another beta in a couple of days.

2015-09-18 17:00 GMT+02:00 Jasm Sison <notifications@github.com>:

> Will do. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobykurien/Xtendroid/issues/81#issuecomment-141476549>
> .
>



-- 
Sven Efftinge

Mobile: +49 175 5274726

web: http://www.itemis.de
mail: sven.efftinge@itemis.de

blog: http://effi-blog.blogspot.com
xing: https://www.xing.com/profile/Sven_Efftinge
linkedin: linkedin.com/in/efftinge
twitter : @svenefftinge

itemis AG
Am Germaniahafen 1
24143 Kiel
Germany

Rechtlicher Hinweis:
Amtsgericht Dortmund, HRB 20621

Vorstand: Jens Wagener (Vors.), Wolfgang Neuhaus, Dr. Georg Pietrek, Jens
Trompeter, Sebastian Neus
Aufsichtsrat: Dr. Burkhard Igel (Vors.), Stephan Grollmann, Michael Neuhaus

**Comment by Buggaboo** [comment] 2015-09-19 10:51
Thanks for the update, I'll try the IDEA route.

**Comment by Buggaboo** [comment] 2015-10-31 14:13
I tried the intellij plugins again recently and on Android Studio 1.5 preview 2 (canary) and Intellij IDEA 15 CE Multiple exceptions occur in the xtext IDEA core plugin 2.9 beta 3 release (@svenefftinge has this been solved?):

Caused by: java.lang.ClassCastException: com.intellij.psi.impl.compiled.ClsFieldImpl cannot be cast to java.lang.Integer at org.eclipse.xtext.idea.common.types.PsiBasedTypeFactory.asInteger(PsiBasedTypeFactory.java:868)

**Comment by svenefftinge** [comment] 2015-11-02 07:06
No that very exception has not been resolved, but we will look at it this
week. I'll keep you posted and it would be really good if you could verify
once it is fixed.

2015-10-31 15:13 GMT+01:00 Jasm Sison <notifications@github.com>:

**Comment by svenefftinge** [comment] 2015-11-02 07:11
I have entered a ticket. 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=481208

Please CC yourself and add any information that could be useful.

**Comment by Buggaboo** [comment] 2015-11-02 15:06
Thanks! I'll keep testing this week. I'll check the [bleeding edge update-site](https://hudson.eclipse.org/xtext/job/xtext-intellij/lastSuccessfulBuild/artifact/git-repo/intellij/build/ideaRepository/updatePlugins.xml), at the end of the week.

**Comment by Buggaboo** [comment] 2015-11-09 12:37
Okay, I've tested [the bleeding edge](https://hudson.eclipse.org/xtext/view/Xtext-Xtend/job/xtext-intellij/lastSuccessfulBuild/artifact/git-repo/intellij/build/ideaRepository/updatePlugins.xml), but now I have a clusterf**k of other issues with IDEA intellij 15 CE, I suspect it's my setup. But the cast issue is gone! \o/

**Comment by svenefftinge** [comment] 2015-11-09 12:57
Could you try to reproduce with a fresh setup or tell us what you did?

2015-11-09 13:37 GMT+01:00 Jasm Sison <notifications@github.com>:

**Comment by tobykurien** [comment] 2015-11-10 05:55
@Buggaboo yes please start a new branch. I'm still waiting for a working stable release of Xtend for Android Studio before spending any effort, but happy that you're willing to give it a go :-)

**Comment by Buggaboo** [comment] 2015-11-12 11:02
Update 12 nov 2015

Update: Attempt to build [XtendApp](https://github.com/tobykurien/XtendApp)

Gradle command-line
* [x] I can build apks with gradle (i.e. `sh ./gradlew clean build`). I install the apk, then I get a missing Activity exception, for some reason the MainActivity is not getting exported. MainActivity is not getting exported for some reason. This is not a problem related to the xtend plug-in whatsoever, but it could affect it. @tobykurien which gradle/groovy version are you using to build XtendApp?

2. I added appcompat-v4, v7, v13 and added a source module of appcompat-v7 to the XtendApp for the styles.xml dependency on supportlib v7 base theme (like we used to do in Eclipse). Android deps are working perfectly. No issues.

3. I have trouble importing xtend classes with active annotations on them. They are simply not being recognized by the plugin. Although the classes are being generated.

For example:
```java
package com.tobykurien.xtendapp.utils;

import android.app.Fragment;
import android.content.Context;
import org.xtendroid.annotations.AndroidPreference;
import org.xtendroid.utils.BasePreferences;

@AndroidPreference
@SuppressWarnings("all")
public class Settings extends BasePreferences {
  private boolean drawerLearned = false;
  
  public static Settings getSettings(final Context context) {
    return BasePreferences.getPreferences(context, Settings.class);
  }
  
  public static Settings getSettings(final Fragment fragment) {
    return BasePreferences.getPreferences(fragment.getActivity(), Settings.class);
  }
  
  public boolean isDrawerLearned() {
    return pref.getBoolean("drawer_learned", drawerLearned);
  }
  
  public boolean setDrawerLearned(final boolean value) {
    pref.edit().putBoolean("drawer_learned", value).commit();
    return true;
  }
}
```

**Comment by tobykurien** [comment] 2015-11-13 08:46
It may be unrelated, but see this issue: https://github.com/xtext/xtend-gradle-plugin/issues/32

Basically, you need to run gradle build twice. The very first build ends up with many errors that don't make any sense.

**Comment by tobykurien** [comment] 2015-11-13 08:51
The latest version (```classpath 'org.xtend:xtend-android-gradle-plugin:0.4.9'```) fixes the issue

**Comment by Buggaboo** [comment] 2015-11-13 16:53
I'll check again this weekend, after applying 0.4.9, both from the IDE and command-line, I'm still getting broken builds though. I was investigating the dex, but I got distracted by paid work...

**Comment by tobykurien** [comment] 2015-11-16 09:53
I've updated the XtendApp build config. I see the same issue you have, and it seems even with v0.4.9 of the xtend gradle plugin, I still have to build twice (if the build directories don't exist). I'm looking into the missing activity class issue.

**Comment by tobykurien** [comment] 2015-11-16 10:06
Fixed the missing class issue, see https://github.com/tobykurien/XtendApp/commit/f5dec987b610f8c70388fdfa6c282280471d007e - obviously an oversight on my part, sorry! :-D

**Comment by Buggaboo** [comment] 2015-11-16 12:59
O damn, I missed the *.activity* change to the MainActivity. That fixed it. I should learn to read Exceptions... my eyes just glaze over after being exposed to so many.

**Comment by tobykurien** [comment] 2015-11-24 06:50
Just tested this on Android Studio 2, and it works!! :-) 

Unfortunately the "Instant Run" feature doesn't work, because it uses ```com.android.tools.build:gradle:2.0.0-beta``` which doesn't play well with Xtend.

**Comment by Buggaboo** [comment] 2015-11-24 09:44
I confirm! Wooohoooooo!

**Comment by tobykurien** [comment] 2015-11-24 10:17
```2.0.0-beta``` doesn't refer to the gradle version, it refers to the android gradle plugin version. Can we close this issue now?

**Comment by Buggaboo** [comment] 2015-11-24 10:30
Which issue? Haha. I hijacked the gitpages with IDE issues.

**Closed** 2016-03-24 10:19 UTC
